version: "2"

services:
  mariadb:
    image: mariadb:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: metastore_db

  hive-metastore:
    build: metastore/
    image: hive-metastore:latest
    ports:
      - 9083:9083
    depends_on:
      - mariadb

  presto:
    image: trinodb/trino
    ports:
      - 8080:8080
    volumes:
      - ./trino/hive.properties:/etc/trino/catalog/hive.properties

  minio:
    image: minio/minio
    environment:
      - MINIO_ACCESS_KEY=accesskey
      - MINIO_SECRET_KEY=secretkey
    volumes:
      - /data1/minio:/data
    ports:
      - 9000:9000
    command: server /data

  create_buckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c '
      sleep 5;
      /usr/bin/mc config host add s3 http://minio:9000 accesskey secretkey --api S3v4;
      /usr/bin/mc mb s3/hive;
      exit 0;
      '
